# Generated by Django 4.2.7 on 2025-06-18 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_api', '0002_invoice_extracted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_data', models.TextField()),
                ('corrected_data', models.TextField()),
                ('used_for_training', models.BooleanField(default=False)),
                ('training_date', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='invoice_api.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('epochs', models.IntegerField(default=3)),
                ('batch_size', models.IntegerField(default=4)),
                ('learning_rate', models.FloatField(default=5e-05)),
                ('results', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('annotations', models.ManyToManyField(related_name='training_jobs', to='invoice_api.invoiceannotation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
